export const TRANSLATE = {
  'Hubei': '湖北省',
  'Zhejiang': '浙江省',
  'Guangdong': '广东省',
  'Henan': '河南省',
  'Hunan': '湖南省',
  'Anhui': '安徽省',
  'Jiangxi': '江西省',
  'Chongqing': '重庆市',
  'Jiangsu': '江苏省',
  'Sichuan': '四川省',
  'Shandong': '山东省',
  'Shanghai': '上海市',
  'Beijing': '北京市',
  'Fujian': '福建省',
  'Shaanxi': '陕西省',
  'Guangxi': '广西壮族自治区',
  'Heilongjiang': '黑龙江省',
  'Hebei': '河北省',
  'Yunnan': '云南省',
  'Liaoning': '辽宁省',
  'Hainan': '海南省',
  'Shanxi': '山西省',
  'Tianjin': '天津市',
  'Gansu': '甘肃省',
  'Guizhou': '贵州省',
  'Inner Mongolia': '内蒙古自治区',
  'Ningxia': '宁夏回族自治区',
  'Jilin': '吉林省',
  'Xinjiang': '新疆维吾尔自治区',
  'Qinghai': '青海省',
  'Tibet': '西藏自治区'
}

export const CORRECTIONS = [
  { provinceName: '黑龙江省', givenName: '大兴安岭', correctName: '大兴安岭地区' },
  { provinceName: '新疆维吾尔自治区', givenName: '兵团第四师', correctName: '可克达拉市' },
  { provinceName: '新疆维吾尔自治区', givenName: '第六师', correctName: '五家渠市' },
  { provinceName: '新疆维吾尔自治区', givenName: '兵团第六师五家渠市', correctName: '五家渠市' },
  { provinceName: '新疆维吾尔自治区', givenName: '第七师', correctName: '克拉玛依市' },
  { provinceName: '新疆维吾尔自治区', givenName: '兵团第七师', correctName: '克拉玛依市' },
  { provinceName: '新疆维吾尔自治区', givenName: '第八师', correctName: '石河子市' },
  { provinceName: '新疆维吾尔自治区', givenName: '第八师石河子', correctName: '石河子市' },
  { provinceName: '新疆维吾尔自治区', givenName: '第八师石河子市', correctName: '石河子市' },
  { provinceName: '新疆维吾尔自治区', givenName: '兵团第八师石河子市', correctName: '石河子市' },
]

export const MUNICIPALITIES = ['北京市', '天津市', '上海市', '重庆市']
